version: '3.8'

services:
  python_app:
    build:
      context: ./python_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./python_app:/app  # <--- Mappa la cartella locale nel container
    working_dir: /app  # <--- Imposta la cartella di lavoro

  go_app:
    build:
      context: ./go_app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: housemanager
      POSTGRES_PASSWORD: housemanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
