version: '3.8'

services:
  python_app:
    build:
      context: ./python_app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - go_app
    volumes:
      - ./python_app:/app
    working_dir: /app
    networks:
      - app-network

  go_app:
    build:
      context: ./go_app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: housemanager
      POSTGRES_PASSWORD: housemanager
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge